import type { 
  Sector, 
  Company, 
  Skill, 
  PlacementStat, 
  SelectionProcess, 
  Alumni, 
  PlacementDrive, 
  InnovationProject, 
  HiringTrend,
  DashboardStats 
} from './types';

// Sectors
export const sectors: Sector[] = [
  { id: '1', name: 'Information Technology', description: 'Software development, IT services, and technology solutions', icon: 'Monitor' },
  { id: '2', name: 'Finance & Banking', description: 'Banking, investment, and financial services', icon: 'Landmark' },
  { id: '3', name: 'Consulting', description: 'Management and business consulting', icon: 'Briefcase' },
  { id: '4', name: 'E-Commerce', description: 'Online retail and digital commerce platforms', icon: 'ShoppingCart' },
  { id: '5', name: 'Healthcare', description: 'Healthcare technology and medical services', icon: 'Heart' },
  { id: '6', name: 'Automotive', description: 'Automobile and mobility solutions', icon: 'Car' },
];

// Companies
export const companies: Company[] = [
  {
    id: '1',
    name: 'Google',
    logo: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png',
    sector_id: '1',
    sector: sectors[0],
    description: 'Google LLC is an American multinational technology company focusing on search engine technology, online advertising, cloud computing, and AI.',
    headquarters: 'Mountain View, California',
    founded_year: 1998,
    employee_count: '150,000+',
    website: 'https://google.com',
    company_type: 'Product',
    min_package: 25,
    max_package: 45,
    avg_package: 35,
    hiring_volume: 15,
    is_featured: true,
  },
  {
    id: '2',
    name: 'Microsoft',
    logo: 'https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1Mu3b?ver=5c31',
    sector_id: '1',
    sector: sectors[0],
    description: 'Microsoft Corporation is an American multinational technology corporation producing computer software, consumer electronics, and related services.',
    headquarters: 'Redmond, Washington',
    founded_year: 1975,
    employee_count: '220,000+',
    website: 'https://microsoft.com',
    company_type: 'Product',
    min_package: 22,
    max_package: 42,
    avg_package: 32,
    hiring_volume: 20,
    is_featured: true,
  },
  {
    id: '3',
    name: 'Amazon',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg',
    sector_id: '4',
    sector: sectors[3],
    description: 'Amazon.com, Inc. is an American multinational technology company focusing on e-commerce, cloud computing, online advertising, and digital streaming.',
    headquarters: 'Seattle, Washington',
    founded_year: 1994,
    employee_count: '1,500,000+',
    website: 'https://amazon.com',
    company_type: 'Product',
    min_package: 20,
    max_package: 40,
    avg_package: 30,
    hiring_volume: 25,
    is_featured: true,
  },
  {
    id: '4',
    name: 'Goldman Sachs',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/6/61/Goldman_Sachs.svg',
    sector_id: '2',
    sector: sectors[1],
    description: 'The Goldman Sachs Group, Inc. is an American multinational investment bank and financial services company.',
    headquarters: 'New York City, New York',
    founded_year: 1869,
    employee_count: '45,000+',
    website: 'https://goldmansachs.com',
    company_type: 'Service',
    min_package: 18,
    max_package: 35,
    avg_package: 26,
    hiring_volume: 12,
    is_featured: true,
  },
  {
    id: '5',
    name: 'McKinsey & Company',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/McKinsey_and_Company_Logo.svg',
    sector_id: '3',
    sector: sectors[2],
    description: 'McKinsey & Company is a global management consulting firm serving leading businesses, governments, and institutions.',
    headquarters: 'New York City, New York',
    founded_year: 1926,
    employee_count: '38,000+',
    website: 'https://mckinsey.com',
    company_type: 'Consulting',
    min_package: 25,
    max_package: 50,
    avg_package: 38,
    hiring_volume: 8,
    is_featured: true,
  },
  {
    id: '6',
    name: 'Infosys',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/9/95/Infosys_logo.svg',
    sector_id: '1',
    sector: sectors[0],
    description: 'Infosys Limited is an Indian multinational corporation that provides business consulting, information technology, and outsourcing services.',
    headquarters: 'Bengaluru, India',
    founded_year: 1981,
    employee_count: '340,000+',
    website: 'https://infosys.com',
    company_type: 'Service',
    min_package: 4,
    max_package: 12,
    avg_package: 6,
    hiring_volume: 150,
    is_featured: false,
  },
  {
    id: '7',
    name: 'TCS',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Tata_Consultancy_Services_Logo.svg',
    sector_id: '1',
    sector: sectors[0],
    description: 'Tata Consultancy Services is an Indian multinational IT services and consulting company.',
    headquarters: 'Mumbai, India',
    founded_year: 1968,
    employee_count: '600,000+',
    website: 'https://tcs.com',
    company_type: 'Service',
    min_package: 3.5,
    max_package: 11,
    avg_package: 5.5,
    hiring_volume: 200,
    is_featured: false,
  },
  {
    id: '8',
    name: 'Flipkart',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/4/49/Flipkart_Logo.svg',
    sector_id: '4',
    sector: sectors[3],
    description: 'Flipkart is an Indian e-commerce company, headquartered in Bangalore, and incorporated in Singapore as a private limited company.',
    headquarters: 'Bengaluru, India',
    founded_year: 2007,
    employee_count: '50,000+',
    website: 'https://flipkart.com',
    company_type: 'Product',
    min_package: 15,
    max_package: 32,
    avg_package: 22,
    hiring_volume: 18,
    is_featured: true,
  },
];

// Skills
export const skills: Skill[] = [
  {
    id: '1',
    name: 'Data Structures & Algorithms',
    category: 'Technical',
    demand_level: 'High',
    related_roles: ['Software Engineer', 'Backend Developer', 'Full Stack Developer'],
    learning_resources: [
      { title: 'LeetCode', url: 'https://leetcode.com' },
      { title: 'GeeksforGeeks', url: 'https://geeksforgeeks.org' },
    ],
    companies_requiring: 45,
  },
  {
    id: '2',
    name: 'Python',
    category: 'Technical',
    demand_level: 'High',
    related_roles: ['Data Scientist', 'Backend Developer', 'ML Engineer'],
    learning_resources: [
      { title: 'Python.org', url: 'https://python.org' },
      { title: 'Real Python', url: 'https://realpython.com' },
    ],
    companies_requiring: 52,
  },
  {
    id: '3',
    name: 'React.js',
    category: 'Technical',
    demand_level: 'High',
    related_roles: ['Frontend Developer', 'Full Stack Developer', 'UI Engineer'],
    learning_resources: [
      { title: 'React Docs', url: 'https://react.dev' },
      { title: 'Scrimba', url: 'https://scrimba.com' },
    ],
    companies_requiring: 38,
  },
  {
    id: '4',
    name: 'Communication',
    category: 'Soft Skills',
    demand_level: 'High',
    related_roles: ['All Roles'],
    learning_resources: [
      { title: 'Coursera Communication', url: 'https://coursera.org' },
    ],
    companies_requiring: 60,
  },
  {
    id: '5',
    name: 'Problem Solving',
    category: 'Soft Skills',
    demand_level: 'High',
    related_roles: ['All Roles'],
    learning_resources: [
      { title: 'HackerRank', url: 'https://hackerrank.com' },
    ],
    companies_requiring: 58,
  },
  {
    id: '6',
    name: 'Git & GitHub',
    category: 'Tools',
    demand_level: 'High',
    related_roles: ['Software Engineer', 'DevOps Engineer'],
    learning_resources: [
      { title: 'Git Documentation', url: 'https://git-scm.com' },
      { title: 'GitHub Learning', url: 'https://skills.github.com' },
    ],
    companies_requiring: 50,
  },
  {
    id: '7',
    name: 'SQL',
    category: 'Technical',
    demand_level: 'Medium',
    related_roles: ['Data Analyst', 'Backend Developer', 'Database Administrator'],
    learning_resources: [
      { title: 'SQLZoo', url: 'https://sqlzoo.net' },
    ],
    companies_requiring: 42,
  },
  {
    id: '8',
    name: 'AWS',
    category: 'Tools',
    demand_level: 'Medium',
    related_roles: ['Cloud Engineer', 'DevOps Engineer', 'Solutions Architect'],
    learning_resources: [
      { title: 'AWS Training', url: 'https://aws.amazon.com/training' },
    ],
    companies_requiring: 35,
  },
];

// Placement Stats
export const placementStats: PlacementStat[] = [
  { id: '1', company_id: '1', year: 2024, students_hired: 15, avg_package: 35, max_package: 45, min_package: 25 },
  { id: '2', company_id: '1', year: 2023, students_hired: 12, avg_package: 32, max_package: 42, min_package: 22 },
  { id: '3', company_id: '2', year: 2024, students_hired: 20, avg_package: 32, max_package: 42, min_package: 22 },
  { id: '4', company_id: '2', year: 2023, students_hired: 18, avg_package: 30, max_package: 40, min_package: 20 },
  { id: '5', company_id: '3', year: 2024, students_hired: 25, avg_package: 30, max_package: 40, min_package: 20 },
  { id: '6', company_id: '4', year: 2024, students_hired: 12, avg_package: 26, max_package: 35, min_package: 18 },
  { id: '7', company_id: '5', year: 2024, students_hired: 8, avg_package: 38, max_package: 50, min_package: 25 },
];

// Selection Processes
export const selectionProcesses: SelectionProcess[] = [
  {
    id: '1',
    company_id: '1',
    rounds: [
      { name: 'Online Assessment', description: 'Coding test with 2-3 problems', duration: '90 mins' },
      { name: 'Technical Interview 1', description: 'DSA and problem solving', duration: '45 mins' },
      { name: 'Technical Interview 2', description: 'System design and projects', duration: '45 mins' },
      { name: 'HR Interview', description: 'Behavioral questions', duration: '30 mins' },
    ],
    eligibility_criteria: ['CGPA >= 7.0', 'No active backlogs', 'B.Tech/M.Tech in CS/IT/ECE'],
    preparation_tips: ['Practice LeetCode medium/hard problems', 'Study system design basics', 'Prepare STAR format answers'],
  },
  {
    id: '2',
    company_id: '2',
    rounds: [
      { name: 'Online Test', description: 'MCQs + Coding', duration: '75 mins' },
      { name: 'Group Discussion', description: 'Topic-based discussion', duration: '20 mins' },
      { name: 'Technical Interview', description: 'CS fundamentals and coding', duration: '60 mins' },
      { name: 'HR Round', description: 'Cultural fit assessment', duration: '30 mins' },
    ],
    eligibility_criteria: ['CGPA >= 6.5', 'No backlogs at interview', 'All branches eligible'],
    preparation_tips: ['Review CS fundamentals', 'Practice group discussions', 'Know your resume well'],
  },
];

// Alumni
export const alumni: Alumni[] = [
  { id: '1', name: 'Rahul Sharma', company_id: '1', role: 'Software Engineer L4', batch: 2022, linkedin_url: 'https://linkedin.com' },
  { id: '2', name: 'Priya Patel', company_id: '1', role: 'Software Engineer L3', batch: 2023, linkedin_url: 'https://linkedin.com' },
  { id: '3', name: 'Amit Kumar', company_id: '2', role: 'SDE 2', batch: 2021, linkedin_url: 'https://linkedin.com' },
  { id: '4', name: 'Sneha Reddy', company_id: '3', role: 'SDE 1', batch: 2023, linkedin_url: 'https://linkedin.com' },
  { id: '5', name: 'Vikram Singh', company_id: '4', role: 'Associate', batch: 2022, linkedin_url: 'https://linkedin.com' },
  { id: '6', name: 'Ananya Gupta', company_id: '5', role: 'Business Analyst', batch: 2023, linkedin_url: 'https://linkedin.com' },
];

// Placement Drives
export const placementDrives: PlacementDrive[] = [
  {
    id: '1',
    company_id: '1',
    company: companies[0],
    date: '2024-03-15',
    roles: ['Software Engineer', 'Cloud Engineer'],
    eligibility: 'CGPA >= 7.0, CSE/IT/ECE',
    registration_deadline: '2024-03-10',
    status: 'Upcoming',
  },
  {
    id: '2',
    company_id: '2',
    company: companies[1],
    date: '2024-03-20',
    roles: ['SDE', 'PM'],
    eligibility: 'CGPA >= 6.5, All Branches',
    registration_deadline: '2024-03-15',
    status: 'Upcoming',
  },
  {
    id: '3',
    company_id: '3',
    company: companies[2],
    date: '2024-02-28',
    roles: ['SDE', 'Data Analyst'],
    eligibility: 'CGPA >= 7.0',
    registration_deadline: '2024-02-25',
    status: 'Ongoing',
  },
];

// Innovation Projects
export const innovationProjects: InnovationProject[] = [
  {
    id: '1',
    title: 'AI-Powered Career Guidance System',
    description: 'Developing an AI system to provide personalized career recommendations based on student profiles and market trends.',
    partners: ['Google', 'IBM'],
    category: 'Artificial Intelligence',
    status: 'Active',
  },
  {
    id: '2',
    title: 'Blockchain Credential Verification',
    description: 'A blockchain-based platform for secure and verifiable academic credentials.',
    partners: ['Microsoft', 'Infosys'],
    category: 'Blockchain',
    status: 'Active',
  },
  {
    id: '3',
    title: 'Smart Campus IoT Network',
    description: 'IoT infrastructure for smart resource management across campus facilities.',
    partners: ['Cisco', 'TCS'],
    category: 'Internet of Things',
    status: 'Completed',
  },
  {
    id: '4',
    title: 'Green Tech Innovation Lab',
    description: 'Research lab focused on sustainable technology solutions for urban environments.',
    partners: ['Tesla', 'Siemens'],
    category: 'Sustainability',
    status: 'Planning',
  },
];

// Hiring Trends
export const hiringTrends: HiringTrend[] = [
  { year: 2020, total_offers: 450, avg_package: 8.5, highest_package: 32, sectors: [{ sector_id: '1', offers: 280 }] },
  { year: 2021, total_offers: 520, avg_package: 9.2, highest_package: 38, sectors: [{ sector_id: '1', offers: 310 }] },
  { year: 2022, total_offers: 680, avg_package: 10.5, highest_package: 42, sectors: [{ sector_id: '1', offers: 400 }] },
  { year: 2023, total_offers: 750, avg_package: 11.8, highest_package: 48, sectors: [{ sector_id: '1', offers: 450 }] },
  { year: 2024, total_offers: 820, avg_package: 12.5, highest_package: 50, sectors: [{ sector_id: '1', offers: 500 }] },
];

// Dashboard Stats
export const dashboardStats: DashboardStats = {
  total_companies: 65,
  avg_package: 12.5,
  highest_package: 50,
  total_placements: 820,
  top_sector: 'Information Technology',
};
